version: '3.8'

services:
  app:
    image: ${DOCKER_USERNAME}/my-app:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge